apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ping-pong
spec:
  tasks:
  - name: ping
    taskSpec:
      steps:
      - name: ping
        image: alpine:3.9
        script: echo 'ping from alpine' && sleep 1 && echo "ping again at $(date)" && sleep 10 && echo "ping end"
      - name: post-ping
        image: alpine:3.9
        script: echo 'happen after ping'
  - name: pong
    taskSpec:
      steps:
      - name: pong
        image: alpine:3.9
        script: sleep 1 && echo 'pong from alpine' && sleep 1 && echo "pong again at $(date)" && echo "pong end" && sleep 10
